<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>92d98aa7-b028-413e-8c1e-af67f4ca1818</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to `Hello { 'Name' }! { 'Weather advice' }` ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
